### ISSUE TITLE
Subnet secondary ranges aren't being removed/updated when changed

### ISSUE THREAD

**Issue by jeheyer** [aws2gcp/gcp-network-terraform#7]
When setting secondary ranges to null or empty list ([]), the existing ranges fail to be removed.  

https://github.com/hashicorp/terraform-provider-google/issues/14878

**Comment by aws2gcp** [comment]
This had been bothering me for a while and I always assumed it was an API limitation or bug.  It's more of a legacy TF provider issue where the work-around isn't clearly explained.

The fix is simply write [secondary_ip_range](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork#secondary_ip_range) as an attribute in the resource, rather than a dynamic block.  This works:

```
resource "google_compute_subnetwork" "default" {
  for_each                   = { for k, v in local.subnets : v.key => v if v.create }
  project                     = var.project_id
  secondary_ip_range = [for i, v in each.value.secondary_ranges : {
    range_name    = v.name
    ip_cidr_range = v.range
  }]
}
```

**Comment by aws2gcp** [comment]
https://github.com/aws2gcp/gcp-network-terraform/commit/0f77c8c5d9b3698e30e29ef8eda9bfc8b2d21944#diff-eb611cce7ca18204d16fbaf315b3ed873d4feb849f7f1623ad63743705f4ed19
